// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.billing-meter-sink@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const BILLING_METER_SINK_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const BILLING_METER_SINK_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_billing_meter_sink { () => { "{\"capability_id\":\"lenso.billing-meter-sink@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"publish_meter_event\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_billing_meter_sink_client { () => { "{\"capability_id\":\"lenso.billing-meter-sink@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_billing_meter_sink_client { () => { "{\"capability_id\":\"lenso.billing-meter-sink@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const PUBLISH_METER_EVENT_OPERATION: &str = "publish_meter_event";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PublishMeterEventRequest {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "meter")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub meter: String,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "quantity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub quantity: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PublishMeterEventResponse {
    #[serde(rename = "accepted")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted: bool,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: PublishMeterEventResponseOutcome,
    #[serde(rename = "provider_reference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_reference: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum PublishMeterEventResponseOutcome {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "replayed")]
    Replayed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PublishMeterEventError {
    AccountNotFound,
    EffectUnknown,
    Forbidden,
    IdempotencyConflict,
    InvalidEvent,
    MeterNotConfigured,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct BillingMeterSink;
impl RequestCapability for BillingMeterSink {
    type Request = PublishMeterEventRequest;
    type Response = PublishMeterEventResponse;
    type DomainError = PublishMeterEventError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PUBLISH_METER_EVENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BillingMeterSinkRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).publish_meter_event(context, request)
    }
}

impl serde::Serialize for PublishMeterEventError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccountNotFound => serializer.serialize_str("account_not_found"),
            Self::EffectUnknown => serializer.serialize_str("effect_unknown"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::MeterNotConfigured => serializer.serialize_str("meter_not_configured"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PublishMeterEventError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "account_not_found" => Ok(Self::AccountNotFound),
                "effect_unknown" => Ok(Self::EffectUnknown),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_event" => Ok(Self::InvalidEvent),
                "meter_not_configured" => Ok(Self::MeterNotConfigured),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_publish_meter_event_request(value: &PublishMeterEventRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_meter_event_request(wire: &str) -> Result<PublishMeterEventRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_publish_meter_event_response(value: &PublishMeterEventResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_meter_event_response(wire: &str) -> Result<PublishMeterEventResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_publish_meter_event_error(value: &PublishMeterEventError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_meter_event_error(wire: &str) -> Result<PublishMeterEventError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoBillingMeterSinkPublishMeterEventResult {
    fn __lenso_into_result(self) -> Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure>;
}
impl __LensoIntoBillingMeterSinkPublishMeterEventResult for Result<PublishMeterEventResponse, PublishMeterEventError> {
    fn __lenso_into_result(self) -> Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBillingMeterSinkPublishMeterEventResult for Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure> { self }
}
impl __LensoIntoBillingMeterSinkPublishMeterEventResult for Result<PublishMeterEventResponse, lenso_plugin_authoring::PluginError<PublishMeterEventError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBillingMeterSinkPublishMeterEventResult for Result<PublishMeterEventResponse, BillingMeterSinkInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PublishMeterEventResponse, PublishMeterEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BillingMeterSinkInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BillingMeterSinkInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait BillingMeterSinkProvider: fmt::Debug + 'static {
    fn publish_meter_event(&self, context: InvocationContext, request: PublishMeterEventRequest) -> NativeRequestFuture<BillingMeterSink>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_billing_meter_sink {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportBillingMeterSink;
        impl $crate::BillingMeterSinkProvider for $plugin {
        fn publish_meter_event(&self, context: __LensoNativeSupportBillingMeterSink::InvocationContext, request: $crate::PublishMeterEventRequest) -> __LensoNativeSupportBillingMeterSink::NativeRequestFuture<$crate::BillingMeterSink> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::publish_meter_event(&plugin, context, request).await;
                $crate::__LensoIntoBillingMeterSinkPublishMeterEventResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct BillingMeterSinkRequestEndpoint { provider: Rc<dyn BillingMeterSinkProvider> }

#[derive(Debug)]
pub struct BillingMeterSinkEndpoint<P: BillingMeterSinkProvider> { provider: Rc<P>, request_endpoint: BillingMeterSinkRequestEndpoint }
impl<P: BillingMeterSinkProvider> BillingMeterSinkEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn BillingMeterSinkProvider> = provider.clone();
        Self { provider, request_endpoint: BillingMeterSinkRequestEndpoint { provider: request_provider } }
    }
}

impl<P: BillingMeterSinkProvider> NativeRequestEndpoint for BillingMeterSinkEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PUBLISH_METER_EVENT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PUBLISH_METER_EVENT_OPERATION => {
                let Ok(request) = request.downcast::<PublishMeterEventRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).publish_meter_event(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_billing_meter_sink {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::BillingMeterSinkEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_billing_meter_sink {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_billing_meter_sink!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct BillingMeterSinkClient {
    publish_meter_event: NativeRequestHandle<BillingMeterSink>,
}
impl BillingMeterSinkClient {
    pub fn new(handle: NativeRequestHandle<BillingMeterSink>) -> Self {
        Self { publish_meter_event: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn publish_meter_event(&self, request: PublishMeterEventRequest) -> Result<PublishMeterEventResponse, BillingMeterSinkInvocationError> {
        self.publish_meter_event.invoke(PUBLISH_METER_EVENT_OPERATION, request).await
            .map_err(BillingMeterSinkInvocationError::Runtime)?
            .map_err(BillingMeterSinkInvocationError::Domain)
    }

    pub async fn publish_meter_event_with_context(&self, context: InvocationContext, request: PublishMeterEventRequest) -> Result<PublishMeterEventResponse, BillingMeterSinkInvocationError> {
        self.publish_meter_event.invoke_with_context(PUBLISH_METER_EVENT_OPERATION, context, request).await
            .map_err(BillingMeterSinkInvocationError::Runtime)?
            .map_err(BillingMeterSinkInvocationError::Domain)
    }
}

impl CapabilityClient for BillingMeterSinkClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            publish_meter_event: dependencies.one::<BillingMeterSink>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for BillingMeterSinkClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    publish_meter_event: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BillingMeterSink>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum BillingMeterSinkInvocationError {
    Domain(PublishMeterEventError),
    Runtime(RuntimeFailure),
}
